"""
This type stub file was generated by pyright.
"""

from .base import Directive

class Admonition(Directive):
    SUPPORTED_NAMES = ...
    def parse(self, block, m, state):
        ...
    
    def __call__(self, md):
        ...
    


def render_html_admonition(text, name, title=...):
    ...

def render_ast_admonition(children, name, title=...):
    ...

