"""
This type stub file was generated by pyright.
"""

"""
    Directive Syntax
    ~~~~~~~~~~~~~~~~~

    This syntax is inspired by reStructuredText. The syntax is very powerful,
    that you can define a lot of custom features by your own.

    The syntax looks like::

        .. directive-name:: directive value
           :option-key: option value
           :option-key: option value

           full featured markdown text here

    :copyright: (c) Hsiaoming Yang
"""
__all__ = ['Directive']
DIRECTIVE_PATTERN = ...
class Directive:
    @staticmethod
    def parse_text(m): # -> str:
        ...
    
    @staticmethod
    def parse_options(m): # -> list[Unknown]:
        ...
    
    def register_directive(self, md, name): # -> None:
        ...
    
    def parse(self, block, m, state):
        ...
    
    def __call__(self, md):
        ...
    


class PluginDirective:
    def __init__(self) -> None:
        ...
    
    def register_directive(self, name, fn): # -> None:
        ...
    
    def parse_block_directive(self, block, m, state): # -> dict[str, Unknown]:
        ...
    
    def __call__(self, md): # -> None:
        ...
    


