"""
This type stub file was generated by pyright.
"""

from .base import Directive

class DirectiveInclude(Directive):
    def parse(self, block, m, state): # -> dict[str, str] | dict[str, Unknown]:
        ...
    
    def __call__(self, md): # -> None:
        ...
    


def render_ast_include(text, relpath, abspath=..., options=...): # -> dict[str, Unknown]:
    ...

def render_html_include(text, relpath, abspath=..., options=...):
    ...

