"""
This type stub file was generated by pyright.
"""

from .base import Directive

class DirectiveInclude(Directive):
    def parse(self, block, m, state):
        ...
    
    def __call__(self, md):
        ...
    


def render_ast_include(text, relpath, abspath=..., options=...):
    ...

def render_html_include(text, relpath, abspath=..., options=...):
    ...

