"""
This type stub file was generated by pyright.
"""

from .markdown import Markdown
from .block_parser import BlockParser
from .inline_parser import InlineParser
from .renderers import AstRenderer, HTMLRenderer
from .scanner import escape, escape_html, escape_url, unikey
from .plugins import PLUGINS

def create_markdown(escape=..., renderer=..., plugins=...):
    """Create a Markdown instance based on the given condition.

    :param escape: Boolean. If using html renderer, escape html.
    :param renderer: renderer instance or string of ``html`` and ``ast``.
    :param plugins: List of plugins, string or callable.

    This method is used when you want to re-use a Markdown instance::

        markdown = create_markdown(
            escape=False,
            renderer='html',
            plugins=['url', 'strikethrough', 'footnotes', 'table'],
        )
        # re-use markdown function
        markdown('.... your text ...')
    """
    ...

html = create_markdown(escape=False, renderer='html', plugins=['strikethrough', 'footnotes', 'table'])
def markdown(text, escape=..., renderer=..., plugins=...):
    ...

__version__ = '2.0.0a6'
