"""
This type stub file was generated by pyright.
"""

import re
from typing import Callable, List

_newline_pattern = re.compile(r'\r\n|\r')
_blank_lines = re.compile(r'^ +$', re.M)
class Markdown(object):
    before_parse_hooks: List[Callable]
    before_render_hooks: List[Callable]
    after_render_hooks: List[Callable]

    def __init__(self, renderer, block=..., inline=..., plugins=...) -> None:
        ...
    
    def use(self, plugin):
        ...
    
    def before_parse(self, s, state):
        ...
    
    def before_render(self, tokens, state):
        ...
    
    def after_render(self, result, state):
        ...
    
    def parse(self, s, state=...):
        ...
    
    def read(self, filepath, state=...):
        ...
    
    def __call__(self, s):
        ...
    


def preprocess(s, state):
    ...

