"""
This type stub file was generated by pyright.
"""

class Markdown:
    def __init__(self, renderer, block=..., inline=..., plugins=...) -> None:
        ...
    
    def use(self, plugin): # -> None:
        ...
    
    def before_parse(self, s, state): # -> tuple[str | Unknown, Unknown]:
        ...
    
    def before_render(self, tokens, state):
        ...
    
    def after_render(self, result, state):
        ...
    
    def parse(self, s, state=...):
        ...
    
    def read(self, filepath, state=...):
        ...
    
    def __call__(self, s):
        ...
    


def preprocess(s, state): # -> tuple[str, Unknown]:
    ...

