"""
This type stub file was generated by pyright.
"""

import re

class Scanner(re.Scanner):
    def iter(self, string, state, parse_text):
        ...
    


class ScannerParser(object):
    scanner_cls = ...
    RULE_NAMES = ...
    def __init__(self) -> None:
        ...
    
    def register_rule(self, name, pattern, method):
        ...
    
    def get_rule_pattern(self, name):
        ...
    
    def get_rule_method(self, name):
        ...
    
    def parse_text(self, text, state):
        ...
    


class Matcher(object):
    PARAGRAPH_END = ...
    def __init__(self, lexicon) -> None:
        ...
    
    def search_pos(self, string, pos):
        ...
    
    def iter(self, string, state, parse_text):
        ...
    


def escape(s, quote=...):
    ...

def escape_url(link):
    ...

def escape_html(s):
    ...

def unikey(s):
    ...

