"""
This type stub file was generated by pyright.
"""

import re

class Scanner(re.Scanner):
    def iter(self, string, state, parse_text): # -> Generator[Unknown, None, None]:
        ...
    


class ScannerParser:
    scanner_cls = Scanner
    RULE_NAMES = ...
    def __init__(self) -> None:
        ...
    
    def register_rule(self, name, pattern, method): # -> None:
        ...
    
    def get_rule_pattern(self, name): # -> Any:
        ...
    
    def get_rule_method(self, name): # -> Any:
        ...
    
    def parse_text(self, text, state):
        ...
    


class Matcher:
    PARAGRAPH_END = ...
    def __init__(self, lexicon) -> None:
        ...
    
    def search_pos(self, string, pos): # -> int | None:
        ...
    
    def iter(self, string, state, parse_text):
        ...
    


