"""
This type stub file was generated by pyright.
"""

from .abbr import plugin_abbr
from .def_list import plugin_def_list
from .extra import plugin_strikethrough, plugin_url
from .footnotes import plugin_footnotes
from .table import plugin_table
from .task_lists import plugin_task_lists

PLUGINS = ...
__all__ = ["PLUGINS", "plugin_url", "plugin_strikethrough", "plugin_footnotes", "plugin_table", "plugin_abbr"]
