"""
This type stub file was generated by pyright.
"""

__all__ = ["plugin_def_list"]
DEFINITION_LIST_PATTERN = ...
def parse_def_list(block, m, state): # -> dict[str, Unknown]:
    ...

def render_html_def_list(text):
    ...

def render_html_def_list_header(text):
    ...

def render_html_def_list_item(text):
    ...

def render_ast_def_list_header(text): # -> dict[str, Unknown]:
    ...

def render_ast_def_list_item(text): # -> dict[str, Unknown]:
    ...

def plugin_def_list(md): # -> None:
    ...

