"""
This type stub file was generated by pyright.
"""

from mistune.inline_parser import ESCAPE

URL_LINK_PATTERN = r'''(https?:\/\/[^\s<]+[^<.,:;"')\]\s])'''
def parse_url_link(self, m, state):
    ...

def plugin_url(md):
    ...

STRIKETHROUGH_PATTERN = r'~~(?=[^\s~])(' r'(?:\\~|[^~])*' r'(?:' + ESCAPE + r'|[^\s~]))~~'
def parse_strikethrough(self, m, state):
    ...

def render_html_strikethrough(text):
    ...

def plugin_strikethrough(md):
    ...

