"""
This type stub file was generated by pyright.
"""

import re
from mistune.inline_parser import LINK_LABEL

INLINE_FOOTNOTE_PATTERN = r'\[\^(' + LINK_LABEL + r')\]'
DEF_FOOTNOTE = re.compile(r'( {0,3})\[\^(' + LINK_LABEL + r')\]:[ \t]*(' r'[^\n]*\n+' r'(?:\1 {1,3}(?! )[^\n]*\n+)*' r')')
def parse_inline_footnote(inline, m, state):
    ...

def parse_def_footnote(block, m, state):
    ...

def parse_footnote_item(block, k, i, state):
    ...

def md_footnotes_hook(md, result, state):
    ...

def render_ast_footnote_ref(key, index):
    ...

def render_ast_footnote_item(children, key, index):
    ...

def render_html_footnote_ref(key, index):
    ...

def render_html_footnotes(text):
    ...

def render_html_footnote_item(text, key, index):
    ...

def plugin_footnotes(md):
    ...

