"""
This type stub file was generated by pyright.
"""

import re

TABLE_PATTERN = re.compile(r' {0,3}\|(.+)\n *\|( *[-:]+[-| :]*)\n((?: *\|.*(?:\n|$))*)\n*')
NP_TABLE_PATTERN = re.compile(r' {0,3}(\S.*\|.*)\n *([-:]+ *\|[-| :]*)\n((?:.*\|.*(?:\n|$))*)\n*')
HEADER_SUB = re.compile(r'\| *$')
HEADER_SPLIT = re.compile(r' *\| *')
ALIGN_SPLIT = re.compile(r' *\| *')
def parse_table(self, m, state):
    ...

def parse_nptable(self, m, state):
    ...

def render_html_table(text):
    ...

def render_html_table_head(text):
    ...

def render_html_table_body(text):
    ...

def render_html_table_row(text):
    ...

def render_html_table_cell(text, align=..., is_head=...):
    ...

def render_ast_table_cell(children, align=..., is_head=...):
    ...

def plugin_table(md):
    ...

