"""
This type stub file was generated by pyright.
"""

import re

TASK_LIST_ITEM = re.compile(r'^(\[[ xX]\])\s(\s*\S.*)')
def task_lists_hook(md, tokens, state):
    ...

def render_ast_task_list_item(children, level, checked):
    ...

def render_html_task_list_item(text, level, checked):
    ...

def plugin_task_lists(md):
    ...

