"""
This type stub file was generated by pyright.
"""

__all__ = ['plugin_task_lists']
TASK_LIST_ITEM = ...
def task_lists_hook(md, tokens, state):
    ...

def render_ast_task_list_item(children, level, checked): # -> dict[str, Unknown]:
    ...

def render_html_task_list_item(text, level, checked):
    ...

def plugin_task_lists(md): # -> None:
    ...

